services:
  db:
    image: postgis/postgis:latest
    restart: no
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build: ./python
    restart: no
    volumes:
      - ./python:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DATABASE_URL=postgresql://postgres:postgres@db/postgres
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
        restart: true

volumes:
  db_data:
