"""Add relation to polymorphic child

Revision ID: a4c09fff2e50
Revises: fbbbbda59b34
Create Date: 2025-02-07 22:07:09.232637

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a4c09fff2e50"
down_revision = "fbbbbda59b34"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("TRUNCATE TABLE public.user RESTART IDENTITY;")
    op.create_table(
        "account",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_foreign_key('user_account_id_fkey', "account", ["account_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_constraint('user_account_id_fkey', type_="foreignkey")

    op.drop_table("account")
    # ### end Alembic commands ###
